### ISSUE TITLE
How to use Exchange-API to send transactions?

### ISSUE THREAD

**Issue by zenghq3** [dfdchain/dfd_project#1]
In https://github.com/dfdchain/dfd_project/wiki/Exchange-API I have seen wallet-related APIs, but I have not seen sending transactions. And the java sdk mentioned at the end does not know the link

**Comment by dfdgroup** [comment]
DFD Java sdk is updated now, plz check out it at (https://github.com/dfdchain/dfd_java_sdk)

**Comment by zenghq3** [comment]
thx
